# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20180516_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Occupation_type'),
        ),
    ]
