# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_auto_20180516_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_introduction',
            name='inter_occupation1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Occupation_type'),
            preserve_default=False,
        ),
    ]
