# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_auto_20180516_0242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mrapply_State',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='mtr_lesson',
            new_name='state_name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='b_categ_num',
        ),
        migrations.AlterField(
            model_name='review',
            name='mrapply_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Mrapply'),
        ),
    ]
