# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_auto_20180516_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrapply',
            old_name='mrapply_con',
            new_name='state_num',
        ),
    ]
